// Generated by gencpp from file valorant_simulation_jarif/yoyo.msg
// DO NOT EDIT!


#ifndef VALORANT_SIMULATION_JARIF_MESSAGE_YOYO_H
#define VALORANT_SIMULATION_JARIF_MESSAGE_YOYO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace valorant_simulation_jarif
{
template <class ContainerAllocator>
struct yoyo_
{
  typedef yoyo_<ContainerAllocator> Type;

  yoyo_()
    : num(0)
    , data()  {
    }
  yoyo_(const ContainerAllocator& _alloc)
    : num(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _num_type;
  _num_type num;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> const> ConstPtr;

}; // struct yoyo_

typedef ::valorant_simulation_jarif::yoyo_<std::allocator<void> > yoyo;

typedef boost::shared_ptr< ::valorant_simulation_jarif::yoyo > yoyoPtr;
typedef boost::shared_ptr< ::valorant_simulation_jarif::yoyo const> yoyoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::valorant_simulation_jarif::yoyo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::valorant_simulation_jarif::yoyo_<ContainerAllocator1> & lhs, const ::valorant_simulation_jarif::yoyo_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::valorant_simulation_jarif::yoyo_<ContainerAllocator1> & lhs, const ::valorant_simulation_jarif::yoyo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace valorant_simulation_jarif

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52023ba745bc86206a9d277c7e36d0e6";
  }

  static const char* value(const ::valorant_simulation_jarif::yoyo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52023ba745bc8620ULL;
  static const uint64_t static_value2 = 0x6a9d277c7e36d0e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "valorant_simulation_jarif/yoyo";
  }

  static const char* value(const ::valorant_simulation_jarif::yoyo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num\n"
"string data\n"
;
  }

  static const char* value(const ::valorant_simulation_jarif::yoyo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yoyo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::valorant_simulation_jarif::yoyo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::valorant_simulation_jarif::yoyo_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VALORANT_SIMULATION_JARIF_MESSAGE_YOYO_H
